# Generated by Django 4.1.1 on 2022-09-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=150)),
                ('cat_race', models.CharField(max_length=150)),
                ('cat_age', models.IntegerField()),
                ('cat_genre', models.CharField(max_length=120)),
                ('cat_color', models.CharField(max_length=50)),
                ('cat_weight', models.CharField(max_length=50)),
            ],
        ),
    ]
